### ISSUE TITLE
All sky camera text

### ISSUE THREAD

**Issue by BobWhaley** [MarkGrimwood/Mognet-All-Sky-Camera-install#21]
Is it possible to remove the time / date / CPU temperature insert from the still pictures so that the camera output can be used with a stacker without ending up with a blur at the top of the picture?

**Comment by MarkGrimwood** [comment]
Hi Bob,

Yes it is possible. Use a text editor, or Nano from the command line to edit the files capture.sh and newmovie.sh in the /backend/pics/ directory, and change the line that reads `IMAGE_TEXT="$HUMANDATE : CPU Temp $CPU_TEMP"` to read `IMAGE_TEXT=""` All images captured captured after that will not be saved with the text, and it won't be displayed on the current view either.

Mark
